language: julia
os:
    - linux
    - windows
julia:
    - 0.5
    # - nightly
notifications:
    email: false
sudo: false
# addons:
#     apt_packages:
#         - gfortran
#         - liblapack-dev
#         - libgmp-dev
#         - libglpk-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    # - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("JuMP")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
